### ISSUE TITLE
Dubtes

### ISSUE THREAD

**Issue by PauRedon** [PauRedon/ASW_G14A#10]
index.html - línia 27, no se'ns redirigeix a la nova pàgina.
_login.htm els forms no ens funcionen, quan fem login es crea un nou usuari i no es fa el login.

A ser possible ens agradaria fer un meet per a poder resoldre millor els dubtes.

**Comment by lidix91** [comment]
He mirat el vostre codi i crec que us falta una "s"
linia  27: <a <%= link_to "news", news_contribucio_path %> </a> |

Al routes.rb teniu  "resources :contribucios", on "contibucios" està en plural, crec que el path hauria de ser news_contribucio**s**_path.

Si voleu fer un meet, ha de ser a partir del 6 d'abril.

**Comment by lidix91** [comment]
He estat mirant el codi i crec que us heu deixat una "s". A l'index.html teniu
<a <%= link_to "news", news_contribucio_path %> </a>

Crec que hauria de ser en plural: <a <%= link_to "news", news_contribucio**s**_path %> </a>

Podeu mirar aquí: [https://guides.rubyonrails.org/routing.html#adding-collection-routes](https://guides.rubyonrails.org/routing.html#adding-collection-routes)

Si voleu un meet, ha de ser a partir del 6 d'abril.
