### ISSUE TITLE
Problemes amb el deploy a Heroku

### ISSUE THREAD

**Issue by PauRedon** [PauRedon/ASW_G14A#12]
Estem fent el deploy a heroku i per a fer-ho utilitzem la funció de heroku de connectar-se al github i fer deploy d'una branch, en el nostre cas hem creat una nova branca anomenada deployment, i alhora de fer el primer deploy ens falla perque el stack que utilitza no soporta la nostra versió del ruby, hem provat a cambiar el stack a un que soportes la nostra versió pero no ens deixa tampoc.

**Comment by lidix91** [comment]
Sembla que esteu fent servir una versió que és incompatible amb l'Heroku. No he trobat on teniu la versió del ruby (no l'he trobat a l'arxiu Gemfile), pero he vist que es fa servir la 2.6.3.

Heu de fer servir un altre, podeu instalar-la fent:
$ bundle _2.3.13_ install --without production
$ git commit -am "Gemfile updated"
