### ISSUE TITLE
Problemes amb la database

### ISSUE THREAD

**Issue by PauRedon** [PauRedon/ASW_G14A#14]
Hem fet el deploy a heroku i se'ns queixaba de que utilitzavem sqlite, hem cambiat a postgres seguint el tutorial de Heroku (https://devcenter.heroku.com/articles/sqlite3) i ens esta donant molts de problemes.

Podries mirar el gemfile i el database.yml i dir-nos si hi ha algo malament?
Agrairiem si puguessim fer un meet i ensenyar-te millor els errors que ens dona

**Comment by joelcrespo00** [comment]
Hem provat a fer un de 0 pero surt el mateix problema. Adjunto la sortida a la consola en fer "rails db:create":


![](https://cdn.discordapp.com/attachments/819962719733940267/833288594265210910/unknown.png)

**Comment by lidix91** [comment]
He contestat per mail a l'Alejandro, ho enganxo aquí per si de cas. 

L'sqlite3 no es pot utilitzar a heroku, heu d'esborrar la linia 11 del Gemfile. L'sqlite3 s'utilitza en l'entron de desenvolupament (tal com ja diu la linia 19 del Gemfile) i a heroku, l'entorn de producció, s'utilitza Postgress (linia 37 del Gemfile).
