### ISSUE TITLE
Redirect back no redirigeix bé

### ISSUE THREAD

**Issue by joelcrespo00** [PauRedon/ASW_G14A#22]

**Comment by lidix91** [comment]
a on?

**Comment by joelcrespo00** [comment]
> a on?

qualsevol de les crides sembla no funcionar, en fer like o dislike, per exemple

**Comment by lidix91** [comment]
quan executeu en local, o quan està desplegat a l'Heroku?

**Comment by lidix91** [comment]
Proveu `format.html { redirect_back(fallback_location: users_comments_url) }`
Si no us funciona per anar a la pàgina que fa la crida també es pot fer servir:  `format.html { redirect_to request.referrer }`

**Comment by joelcrespo00** [comment]
No va, ens diu "too few arguments" provant de les dues maneres, i fins i tot afegint un notice



![image](https://user-images.githubusercontent.com/79398688/117533695-79794500-afee-11eb-9daa-4cfadf6a1529.png)

![image](https://user-images.githubusercontent.com/79398688/117533701-8bf37e80-afee-11eb-93e7-57dd50d95fe2.png)

**Comment by lidix91** [comment]
Aquest tema no es rellevant per la segona entrega, el que ha de funcionar són les crides que retornen JSON, això fa que no funcionin els JSONs?
