### ISSUE TITLE
Meet abans de la segona entrega

### ISSUE THREAD

**Issue by joelcrespo00** [PauRedon/ASW_G14A#24]
Podriem fer un meet abans de la segona entrega. Tot el que ens falta son els llistats d'un usuari, però no ens aclarem a l'hora de deifnir les rutes per accedir-hi (igual no s'entén però explicat per paraula s'entén millor), creiem que ens estem complicant massa la vida.
Pots trobar les rutes o bé a "views/users/show.html" o bé a l'arxiu de la carpeta arrel "routes.txt"

**Comment by lidix91** [comment]
Les rutes dels llistats, són le mateixes que feu servir als links que heu posat a la vista de l'usuari.
```
 <strong><a href="/contribucios/users?id=<%=@user.id %>" > Contribucions</a></strong>
    <strong><a href="/comments/users?id=<%=@user.id %>" > Comments</a></strong>
    <% if @user = current_user %>
        <strong><a href="/contribucios/liked/users?id=<%=@user.id %>">Liked</a></strong>
        <strong><a href="/comments/commented/users?id=<%@user.id %>">Commented</a></strong>
```

El que passa és que no les heu definit correctament seguint l'estandar. Per aquestes funcionalitats, les rutes correctes serien:
* /contribucios/users?id= hauria de ser /contribucios?by_userid=
* /comments/users?id= hauria de ser /comments?by_userid=
* /contribucios/liked/users?id= hauria de ser /contribucios?liked_by_userid=
* /comments/commented/users?id= Si aquest són els comentaris que ha fet like, hauria de ser  /comments?liked_by_userid=
