### ISSUE TITLE
POSTs del swagger

### ISSUE THREAD

**Issue by joelcrespo00** [PauRedon/ASW_G14A#25]
No ens funcionen els metodes POST al swagger (no es fa ni la crida al servidor). Pots trobar l'especificació a la carpeta arrel.

**Comment by lidix91** [comment]
Ara miro el yalm que teniu a l'arrel, recordeu que per l'entrega ha d'estar a la carpeta "api". Si és pel tema dels paràmetres, recordeu que els paràmetres del POST van com a body (requestBody), no com a parèmetres.
Us passo l'exemple del POST dels tweets del wall of tweets:
```
  /tweets:
    post:
      tags:
      - tweets
      summary: Adds a new Tweet to the Wall of Tweets
      operationId: addTweet
      requestBody:
        description: Provide the author & content of the new Tweet
        content:
          application/json:
            schema:
              required:
              - author
              - content
              type: object
              properties:
                author:
                  type: string
                  minLength: 4
                  example: 'My name'
                content:
                  type: string
                  minLength: 4
                  maxLength: 280
                  example: 'My content'
        required: true
      responses:
        201:
          description: Tweet created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTweetResult'
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error400'
```

**Comment by lidix91** [comment]
Els paràmetres sembla que están definits correctment, no he pogut provar perquè teniu algún problema amb el desplegament. He provat posant la URL de l'Heroku que teniu al README i no he pogut ni provar el GET de les contribucions, em dona el següent error:
Failed to fetch.Possible Reasons:
* CORS
* Network 
* FailureURL scheme must be "http" or "https" for CORS request.
