### ISSUE TITLE
Filtre del llistat contribucions upvoted

### ISSUE THREAD

**Issue by joelcrespo00** [PauRedon/ASW_G14A#27]
Hem fet els llistats dels usuaris tal com ens has dit. Ens faltaria el de contribucions upvoted, pero no trobem la manera de afegir cada contribucio que compleix els requisits a la coleccio total. Adjuntem captura del codi tal com el tenim.
![image](https://user-images.githubusercontent.com/79398688/117841395-50baaf00-b27d-11eb-8e5a-97e92058c5ea.png)

**Comment by lidix91** [comment]
mireu aquí: [https://guides.rubyonrails.org/active_record_querying.html#joins](https://guides.rubyonrails.org/active_record_querying.html#joins)
